#!/bin/zsh

function ss() {
  SPIN_URL=`spin show -o fqdn`
  ssh spin@${SPIN_URL} -t 'tmux -CC new -A -s tmssh'
}

# fixup lets you choose a commit to fix up and it automatically applies the 
# stages changes in git as a fixup commit and applies it by rebasing off 
# the main / master branch automatically
# Usage: fixup
function fixup() {
  STAGED_CHANGES=`git diff --name-only --cached`
  [[ -z $STAGED_CHANGES ]] && echo "No staged changes to fixup. Exiting..." && exit

  COMMIT_SHA=`git log -n 50 --pretty=format:'%h %s' --no-merges | fzf | cut -c -7`
  git commit --fixup $COMMIT_SHA

  DEFAULT_BRANCH=`git rev-parse --abbrev-ref origin/HEAD | sed 's/origin\///g'`
  GIT_SEQUENCE_EDITOR=true git rebase -i --autosquash $DEFAULT_BRANCH
}

# spin specific aliases
if [[ -v SPIN ]]; then
  alias fqdn="cat /etc/spin/machine/fqdn"
else

fi

alias new-maintenance-task='bin/rails generate maintenance_tasks:task'
alias gitclean='git branch --merged | egrep -v "(^\*|master|main)" | xargs git branch -d'
alias web="dev cd web"
alias core="dev cd shopify"
alias business="dev cd business-platform"
alias shopify="dev cd shopify"
alias identity="dev cd identity"
alias bank="dev cd banking"
alias banking="dev cd banking"
alias please="sudo"
alias aliases="vim ~/.aliases"
alias pull="git pull"
alias rt="ruby -Itest"
alias zshrc="vim ~/.zshrc"
alias resource="source ~/.zshrc"
alias gitconfig="vim ~/.gitconfig"
alias gitaliases="vim ~/.gitconfig"
alias be="bundle exec"
