#!/bin/zsh

# Set editor and visual if code command exists.
if command -v code &> /dev/null; then
  export {EDITOR,VISUAL}="code"
else
  export {EDITOR,VISUAL}="vim"
fi

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export PATH="/usr/local/share/chruby:$PATH"
export ZSH_THEME="ryanseys"
export DISABLE_UPDATE_PROMPT="true"

plugins=(git history-substring-search zsh-autosuggestions zsh-completions ruby zsh-syntax-highlighting ssh-agent)

# Disable Homebrew analytics
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_ENV_HINTS=1

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=7'

source $ZSH/oh-my-zsh.sh

[[ -x /opt/homebrew/bin/brew ]] && eval $(/opt/homebrew/bin/brew shellenv)

# git fuzzy - https://github.com/bigH/git-fuzzy
[ -d "/Users/ryanseys/code/git-fuzzy/bin" ] && export PATH="/Users/ryanseys/code/git-fuzzy/bin:$PATH"

source ~/.aliases
source ~/.aliases_local
source ~/.zshrc_local

[[ -f /opt/dev/sh/chruby/chruby.sh ]] && { type chruby >/dev/null 2>&1 || chruby () { source /opt/dev/sh/chruby/chruby.sh; chruby "$@"; } }

# Dev related.
export PATH=$PATH:/opt/homebrew/bin
export PATH="$HOME/bin:$PATH"
export PATH="/opt/homebrew/opt/mysql-client@5.7/bin:$PATH"

# chruby setup
if [[ -x /opt/homebrew/opt/chruby/share/chruby/chruby.sh ]]
then
  source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
  source /opt/homebrew/opt/chruby/share/chruby/auto.sh
fi

# Ngrok completions
if command -v ngrok &>/dev/null; then
  eval "$(ngrok completion)"
fi

# shadowenv
eval "$(shadowenv init zsh)"

# do not auto-untap homebrew
export GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED=1

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
# cloudplatform: add Shopify clusters to your local kubernetes config
export KUBECONFIG=${KUBECONFIG:+$KUBECONFIG:}/Users/ryanseys/.kube/config:/Users/ryanseys/.kube/config.shopify.cloudplatform
export PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH"
