#!/bin/zsh

# Set editor and visual if code command exists.
if command -v code &> /dev/null; then
  export {EDITOR,VISUAL}="code"
else
  export {EDITOR,VISUAL}="vim"
fi

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export PATH="$PATH:/Applications/RubyMine.app/Contents/MacOS"

ZSH_THEME="ryanseys"
DISABLE_UPDATE_PROMPT="true"
HOMEBREW_NO_ENV_HINTS="true"

plugins=(git history-substring-search zsh-autosuggestions zsh-completions ruby zsh-syntax-highlighting ssh-agent)

# Disable Homebrew analytics
export HOMEBREW_NO_ANALYTICS=1

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=7'

source $ZSH/oh-my-zsh.sh

[[ -x /opt/homebrew/bin/brew ]] && eval $(/opt/homebrew/bin/brew shellenv)

# git fuzzy - https://github.com/bigH/git-fuzzy
[ -d "/Users/ryanseys/code/git-fuzzy/bin" ] && export PATH="/Users/ryanseys/code/git-fuzzy/bin:$PATH"

source ~/.aliases
source ~/.aliases_local
source ~/.zshrc_local


# bun completions
[ -s "/Users/ryanseys/.bun/_bun" ] && source "/Users/ryanseys/.bun/_bun"

# chruby setup
if [[ -x /opt/homebrew/bin/brew ]]
then
  source /usr/local/share/chruby/chruby.sh
  source /usr/local/share/chruby/auto.sh
fi

# shadowenv
eval "$(shadowenv init zsh)"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
